services:
  vector:
    image: timberio/vector:0.43.0-debian
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
    ports:
      - "4317:4317"

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - "4317:4317"
  #     - "4318:4318"

  jaeger:
    image: jaegertracing/all-in-one:latest
    # environment:
    #   - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '16686:16686'