global:
  scrape_interval: 15s

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name

scrape_configs:
  - job_name: 'metrics'
    static_configs:
    - targets: ['vector:9598']